### ISSUE TITLE
Ten years after — v2.0

### ISSUE THREAD

**Issue by briatte** [briatte/srqm#31]
This course is now roughly 10 years old. The pretty dirty repo history shows it. It's time to think of __version 2.0__, although version 1.0 never got its release tag (they did not even exist when we started).

- [ ] Update the __overall code__ to whatever Stata compatibility we choose: see #28 
- [ ] Update the __datasets__ — see #24, #29 and #30
- [ ] Update the __utilities__ in `setup`, especially unpublished ones; see also #26 
- [ ] Rebase the __repository__ for cleanliness?

And perhaps even more importantly:

- [ ] Update the __Stata Guide__
  - [ ] Continue the LaTeX rewrite
  - [ ] Take decade-old comments from Filip, Joël… into account
  - [ ] Finish writing the regression bits using Bittmann 2019 and Mehmetoglu and Jakobsen
- [ ] Update the __course slides__ (let's stick with LaTeX despite love/hate)

## Additional datasets

See #30 for the update discussion, and the suggestion in #24.

## Additional do-files

My many `TODO` files from 2017, (especially) 2018, 2019, 2020 have suggestions of __extra do-files__ to create — shorter ones, ones that cover extra stuff beyond the scope of the course (e.g. merging, panel data).

I also have some __very short "demo" do-files__ that I use in the first hour, as recaps of the previous session + introduction to the second hour of the current one.

## Listing all instructors

I don't think I have the entire list. The README does not list, for instance, Siyavash, or the two girls I met once each to brief them on the course material.

## Beyond teaching

I once considered publishing the Stata Guide, but publishing a Stata Guide, even though some publishers would take it, sounds bizarre in 2021. R is the current standard, with Julia and Python probably coming next or along.

- At least look at LeanPub, [like Roger D. Peng](http://www.biostat.jhsph.edu/~rpeng/books.html).
- Ask PSIA or the Presses de Sciences Po about it.
- Go for Sage, like some kind of updated, no-menus Mehmetoglu and Jakobsen?
